name: "Terraform DEV â€“ Apply"

on:
  push:
    branches:
      - main
    paths:
      - "lab02/infra/**"

  workflow_dispatch: {}

permissions:
  id-token: write       # necesario para OIDC
  contents: read

env:
  TF_WORKING_DIR: lab02/infra/environments/dev

jobs:
  apply:
    runs-on: ubuntu-latest
    name: "Terraform Apply DEV"
    environment: dev   # puedes proteger este environment en GitHub

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ðŸ” Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ðŸ”‘ Export Azure credentials for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      - name: ðŸ” Export PostgreSQL admin password
        run: echo "TF_VAR_pg_admin_password=${{ secrets.PG_ADMIN_PASSWORD_DEV }}" >> $GITHUB_ENV

      - name: ðŸ§± Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: âœ… Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: ðŸš€ Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve
